### Send Email via Unosend API
POST https://www.unosend.co/api/v1/emails
Authorization: Bearer un_iGwCw0L2kW275vE7XUmBl4DF1VeXjYi-
Content-Type: application/json

{
    "from": "noreply@akhlasahmed.online",
    "to": ["akhlasahmed.aka@gmail.com"],
    "subject": "Testing Unosend API",
    "html": "<h1>Hello Adeel!</h1><p>This is a test email sent via REST Client.</p>"
}