import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst } from "workbox-strategies";

clientsClaim();

// Precache all assets generated by Docusaurus
precacheAndRoute(self.__WB_MANIFEST);

// SPA routing
registerRoute(
  ({ request, url }) => request.mode === "navigate",
  createHandlerBoundToURL("/index.html"),
);

// Cache JS/CSS files
registerRoute(
  ({ request }) =>
    request.destination === "script" || request.destination === "style",
  new StaleWhileRevalidate({
    cacheName: "static-resources",
  }),
);

// Cache API requests (optional)
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.startsWith("/api/"),
  new StaleWhileRevalidate({ cacheName: "api-cache" }),
);
